//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietdathang
    {
        public int idhoadon { get; set; }
        public int idhang { get; set; }
        public decimal giaban { get; set; }
        public short soluong { get; set; }
        public float mucgiamgia { get; set; }
    
        public virtual dondathang dondathang { get; set; }
        public virtual mathang mathang { get; set; }
    }
}
