//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dondathang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dondathang()
        {
            this.chitietdathang = new HashSet<chitietdathang>();
        }
    
        public int idhoadon { get; set; }
        public string makhachhang { get; set; }
        public string manhanvien { get; set; }
        public Nullable<System.DateTime> ngaydathang { get; set; }
        public Nullable<System.DateTime> ngaygiaohang { get; set; }
        public Nullable<System.DateTime> ngaychuyenhang { get; set; }
        public string noigiaohang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietdathang> chitietdathang { get; set; }
    }
}
