//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachhang
    {
        public int idkhachhang { get; set; }
        public string tencongty { get; set; }
        public string tengiaodich { get; set; }
        public string diachi { get; set; }
        public string email { get; set; }
        public string dienthoai { get; set; }
        public string fax { get; set; }
    }
}
