//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mathang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mathang()
        {
            this.chitietdathang = new HashSet<chitietdathang>();
        }
    
        public int idhang { get; set; }
        public string tenhang { get; set; }
        public string macongty { get; set; }
        public Nullable<int> maloaihang { get; set; }
        public Nullable<int> soluong { get; set; }
        public string donvitinh { get; set; }
        public Nullable<decimal> giahang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietdathang> chitietdathang { get; set; }
    }
}
