//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ql_banhangEntities : DbContext
    {
        public ql_banhangEntities()
            : base("name=ql_banhangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chitietdathang> chitietdathang { get; set; }
        public virtual DbSet<dondathang> dondathang { get; set; }
        public virtual DbSet<khachhang> khachhang { get; set; }
        public virtual DbSet<loaihang> loaihang { get; set; }
        public virtual DbSet<mathang> mathang { get; set; }
        public virtual DbSet<nhacungcap> nhacungcap { get; set; }
        public virtual DbSet<nhanvien> nhanvien { get; set; }
    }
}
