//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien
    {
        public int idnhanvien { get; set; }
        public string ho { get; set; }
        public string ten { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public Nullable<System.DateTime> ngaylamviec { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
        public Nullable<decimal> luongcoban { get; set; }
        public Nullable<decimal> phucap { get; set; }
    }
}
